#!/bin/bash

sudo pacman -Syu --noconfirm

sudo pacman -S --needed --noconfirm \
    vscode \
    base \
    xorg-server \
    i3-wm \
    i3status \
    gdm \
    gnome \
    gnome-extra \
    git \
    wget \
    curl \
    vi \
    openssh \
    wezterm \
    bluez \
    blueman \
    firefox -y

sudo pacman -S --needed --noconfirm \
    i3 \
    i3blocks \
    rofi \
    dmenu \
    scrot \
    imagemagick \
    terminator \
    picom \
    lxappearance \
    pavucontrol \
    thunar \
    feh \
    playerctl \
    neofetch -y

sudo systemctl enable sshd
sudo systemctl start sshd

sudo systemctl enable gdm
sudo systemctl start gdm

sudo systemctl enable bluetooth
sudo systemctl start bluetooth

# MesloLGS Nerd font
sudo mkdir -p /usr/share/fonts/MesloLGS/ &&
cd /usr/share/fonts/MesloLGS/ && {
sudo rm -rf MesloLGS\*.ttf
sudo wget "https://cloudgeniuscode.s3-us-west-2.amazonaws.com/MesloLGS NF Regular.ttf"
sudo wget "https://cloudgeniuscode.s3-us-west-2.amazonaws.com/MesloLGS NF Italic.ttf"
sudo wget "https://cloudgeniuscode.s3-us-west-2.amazonaws.com/MesloLGS NF Bold.ttf"
sudo wget "https://cloudgeniuscode.s3-us-west-2.amazonaws.com/MesloLGS NF Bold Italic.ttf"
cd -; }

sudo fc-cache -vf /usr/share/fonts/

rm -rf ~/.wezterm.lua
ln -s /home/cloudgenius/i3config/wezterm.lua ~/.wezterm.lua

rm -rf ~/.config/i3/config
ln -s /home/cloudgenius/i3config/mbpconfig ~/.config/i3/config

rm -rf ~/.config/i3/i3blocks.conf
ln -s /home/cloudgenius/i3config/config/i3blocks.conf ~/.config/i3/i3blocks.conf

rm -rf ~/.config/terminator
ln -s ~/i3config/config/terminator ~/.config/terminator

rm -rf ~/.config/rofi
ln -s ~/i3config/config/rofi ~/.config/rofi

rm -rf ~/Documents/bash
ln -s ~/i3config/bash ~/Documents/bash

rm -rf ~/Pictures/wallpapers
ln -s ~/i3config/wallpapers ~/Pictures/wallpapers

rm -rf ~/.bash_aliases
ln -s ~/i3config/.bash_aliases ~/.bash_aliases

rm -rf ~/.Xmodmap
ln -s ~/i3config/.Xmodmap ~/.Xmodmap

rm -rf ~/.xinitrc
ln -s ~/i3config/.xinitrc ~/.xinitrc

rm -rf ~/.config/autostart/xmodmap.desktop
mkdir -p ~/.config/autostart
ln -s ~/i3config/config/autostart/xmodmap.desktop  ~/.config/autostart/xmodmap.desktop

# tap to click
sudo rm -rf /etc/X11/xorg.conf.d/90-touchpad.conf
sudo ln -s ~/i3config/90-touchpad.conf /etc/X11/xorg.conf.d/90-touchpad.conf

# hidpi
# tap to click
rm -rf ~/.Xresources
ln -s ~/i3config/.Xresources ~/.Xresources

# bashrc
rm -rf ~/.bashrc
ln -s ~/i3config/.bashrc ~/.bashrc
